config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  resources :tops, only: [:show, :new, :create]
  resources :chats, only: [:index, :create]
  resources :admins, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :prefecture
  belongs_to :staff
  has_many :prs, through: :pr_jobs
end

app/models/pr.rb
class Pr < ApplicationRecord
  has_many :jobs, through: :pr_jobs
  has_many :pr_jobs
end

app/models/pr_job.rb
class PrJob < ApplicationRecord
  belongs_to :pr
  belongs_to :job
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :jobs
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :jobs
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @jobs = Job.all
  end
  
  def new
    @job = Job.new
  end

  def create
    @job = Job.create(job_params)
  end

  private

  def job_params
    params.require(:job).permit(:title, :image1, :image2, :image3, :image4, :image5, :description, :salary, :access, :time, :week, :employee, :term)
  end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/_Vacancies_info.html.haml
.Title
  = link_to new_admin_path, class: "Title__text" do
    新規案件を登録する
%ul.Bottom-wrapper
  %li.Contents
    .Top-content
    %table.Middle-content
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
    .Bottom-content
      = link_to 'http://www.pikawaka.com', class: "Bottom-Contents__btn" do
        編集
      = link_to 'http://www.pikawaka.com', class: "Bottom-Contents__btn" do
        削除

app/views/admins/_Vacancies_lists.html.haml
.Wrapper
  .Title-wrapper
    求人情報
  = form_with model: job, url: admins_path, html: {class: "Job-wrapper"}, local: true do |form|
    .User-contents__title
      【仕事のキャッチコピーを入力】
      = form.text_field :title, maxlength: 64, class: 'Upper-contents__name', placeholder: 'ここに文章を入力してください'
    .Image-contents
      .Image-contents__post
        【写真掲載】
      %ul.Job-images
        %li.Job-images__list1
          = form.label :image, class: "Job-images__list1--img" do
            = icon('fas', 'image')
            = form.file_field :image, class: 'Job-images__list1--file'
        %li.Job-images__list
        %li.Job-images__list
        %li.Job-images__list
        %li.Job-images__list
    .Vacancy-contents
      .Vacancy-title
        【求人詳細記入】
      %table.Vacancy-infos
        %tr.Vacancy-item
          %td.Vacancy-item__left
            勤務地
          %td.Vacancy-item__right
            = form.text_field :text, placeholder: 'ここに文章を入力してください'
        %tr.Vacancy-item
          %td.Vacancy-item__left
            給与
          %td.Vacancy-item__right
            = form.text_field :text, placeholder: 'ここに文章を入力してください'
        %tr.Vacancy-item
          %td.Vacancy-item__left
            アクセス
          %td.Vacancy-item__right
            = form.text_field :text, placeholder: 'ここに文章を入力してください'
        %tr.Vacancy-item
          %td.Vacancy-item__left
            勤務時間
          %td.Vacancy-item__right
            = form.text_field :text, placeholder: 'ここに文章を入力してください'
        %tr.Vacancy-item
          %td.Vacancy-item__left
            曜日・日数
          %td.Vacancy-item__right
            = form.text_field :text, placeholder: 'ここに文章を入力してください'
        %tr.Vacancy-item
          %td.Vacancy-item__left
            募集人数
          %td.Vacancy-item__right
            = form.text_field :text, placeholder: 'ここに文章を入力してください'
        %tr.Vacancy-item
          %td.Vacancy-item__left
            契約期間
          %td.Vacancy-item__right
            = form.text_field :text, placeholder: 'ここに文章を入力してください'
        %tr.Vacancy-item
          %td.Vacancy-item__left
            営業担当
          %td.Vacancy-item__right
            = form.text_field :text, placeholder: 'ここに文章を入力してください'
        %tr.Vacancy-item
          %td.Vacancy-item__left
            都道府県
          %td.Vacancy-item__right
            = form.text_field :text, placeholder: 'ここに文章を入力してください'
      .Staff-contents
        .Staff-contents__title
          【担当営業】
        .Sales-staffs
          .Sales-staff__name
            "山田 太郎"
          .Sales-staff__name
            "石倉 香"
          .Sales-staff__name
            "山口 上"
      .Pr-contents
        .Pr-title
          PRポイント
        .Pr-box
          .Pr-box__text
            残業ほぼなしカジュアルOK！
          .Pr-box__text
            あっとホーム環境◎
          .Pr-box__text
            引継ぎしっかり！
          .Pr-box__text
            引継ぎしっかり
    .Button-wrapper
      = form.submit '掲載する', class: 'Button-wrapper__button'

app/views/admins/create.html.haml
.Messate
  投稿が完了しました

app/views/admins/index.html.haml
= render partial: "Vacancies_info"

app/views/admins/new.html.haml
= render partial: 'Vacancies_lists', locals: { job: @job }

app/views/chats/_chat.html.haml
.Job-staff
  = image_tag 'image.png', class: 'Job-staff__img'
  .Job-staff__message
    私にお任せください！

.Chat-wrapper
  .Chat-wrapper__title
    質問してね！
  .Chat-wrapper__list
    .Chat-wrapper__list--text
      つつつつううううううううううううううううううう
    .Chat-box
      = form_with url: "#" do |form|
        = form.text_area :text, maxlength: 250, class: 'Chat-box__text', placeholder: 'ここに文章を入力してください'
        .Review-button
          = form.submit '送信する'

.Chat-wrapper__down
  = image_tag 'image.png', class: 'Chat-wrapper__down--image'

.Form-wrapper
  = form_with url: "#" do |form|
    .Form-item
      .Form-item__left
        お名前
      .Form-item__right
        = form.text_field :text, maxlength: 20, class: 'Form-item__right--text', placeholder: 'ここに文章を入力してください'
    .Form-item
      .Form-item__left
        電話番号
      .Form-item__right
        = form.text_field :text, maxlength: 20, class: 'Form-item__right--text', placeholder: 'ここに文章を入力してください'
    .Form-item
      .Form-item__left
        email
      .Form-item__right
        = form.email_field :text, maxlength: 30, class: 'Form-item__right--text', placeholder: 'ここに文章を入力してください'
    .Form-item
      .Form-item__left
        メッセージ
      .Form-item__right
        = form.text_area :text, maxlength: 250, class: 'Form-item__right--text', placeholder: 'ここに文章を入力してください'
    .Form-button
      = form.submit '送信する'

app/views/chats/index.html.haml
.Wrapper
  .Title-wrapper
    仕事内容
  .Job-wrapper
    .Upper-contents
      .Upper-contents__name
        残業なしカジュアルOK！ あっとホーム環境◎ 引継ぎしっかり◎
    .Pr-contents
      .Pr-title
        PRポイント
      .Pr-box
        .Pr-box__text
          テストテストテストテストテストテストテストテスト
        .Pr-box__text
          テストテストテストテストテストテストテストテスト
        .Pr-box__text
          テストテストテストテストテストテストテストテスト
    .Image-contents
      %ul.Job-images
        %li.Job-images__list1
          1
        %li.Job-images__list
          2
        %li.Job-images__list
          3
        %li.Job-images__list
          4
        %li.Job-images__list
          5
    .Vacancy-contents
      %table.Vacancy-infos
        %tr.Vacancy-item
          %td.Vacancy-item__left
            勤務地
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            給与
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            アクセス
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            勤務時間
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            曜日・日数
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            募集人数
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            契約期間
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            営業担当
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            都道府県
          %td.Vacancy-item__right
            テスト
  = render "chat"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DispatchSite
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  .Footer
    .Footer-logo
      COMPANY LOGO
    .Footer-right
      = image_tag 'image.png', class: 'Footer-right__img'
      = link_to admins_path, class: "Footer-right__text" do
        企業担当者はこちら
      .Footer-right__signup
        Sign Up
  = yield
  .Header

app/views/tops/index.html.haml
.Top-wrapper
  = image_tag 'image.png', class: 'Top-wrapper__image'
  .Top-wrapper__login
    Login

.Info-wrapper
  .Title
    新着情報
  .Message-lists
    .Message-lists__box
      .Message-lists__box--date
        2020/08/24
      .Message-lists__box--message
        キャプションキャプションキャプションキャプションキャプション
    .Message-lists__box
      .Message-lists__box--date
        2020/08/24
      .Message-lists__box--message
        キャプションキャプションキャプションキャプションキャプション
    .Message-lists__box
      .Message-lists__box--date
        2020/08/24
      .Message-lists__box--message
        キャプションキャプションキャプションキャプションキャプション
    .Message-lists__box
      .Message-lists__box--date
        2020/08/24
      .Message-lists__box--message
        キャプションキャプションキャプションキャプションキャプション

.Message-wrapper
  .Message-title
    仕事内容一覧
  .Search-box
    = form_with url: "#" do |form|
      = form.text_field :text, class: 'Seach-box__input', placeholder: '仕事を検索する'
      = form.submit '検索', class: 'Search-box__button'

%ul.Bottom-wrapper
  %li.Contents
    .Top-content
    %table.Middle-content
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
    .Bottom-content
      = link_to 'http://www.pikawaka.com', class: "Bottom-Contents__btn" do
        検索
      = image_tag 'image.png', class: 'Bottom-content__like'
  %li.Contents
    .Top-content
    %table.Middle-content
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
    .Bottom-content
      = link_to 'http://www.pikawaka.com', class: "Bottom-Contents__btn" do
        検索
      = image_tag 'image.png', class: 'Bottom-content__like'
  %li.Contents
    .Top-content
    %table.Middle-content
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
    .Bottom-content
      = link_to 'http://www.pikawaka.com', class: "Bottom-Contents__btn" do
        検索
      = image_tag 'image.png', class: 'Bottom-content__like'
  %li.Contents
    .Top-content
    %table.Middle-content
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
    .Bottom-content
      = link_to 'http://www.pikawaka.com', class: "Bottom-Contents__btn" do
        検索
      = image_tag 'image.png', class: 'Bottom-content__like'
  %li.Contents
    .Top-content
    %table.Middle-content
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
      %tr.Text-content
        %td.Text-content__left
          仕事内容
        %td.Text-content__right
          テストテストテスト
    .Bottom-content
      = link_to 'http://www.pikawaka.com', class: "Bottom-Contents__btn" do
        検索
      = image_tag 'image.png', class: 'Bottom-content__like'
  

app/views/tops/new.html.haml
.Wrapper
  .Title-wrapper
    求人情報
  .Job-wrapper
    = form_with url: "#" do |form|
      .Upper-contents
        .User-contents__title
          【仕事のキャッチコピーを入力】       
        = form.text_field :text, maxlength: 64, class: 'Upper-contents__name', placeholder: 'ここに文章を入力してください'      
      .Image-contents
        .Image-contents__post
          【写真掲載】
        %ul.Job-images
          %li.Job-images__list1
            = form.label :image, class: "Job-images__list1--img" do
              = icon('fas', 'image')
              = form.file_field :image, class: 'Job-images__list1--file'
          %li.Job-images__list
            = form.label :image, class: "Job-images__list--img" do
              = icon('fas', 'image')
              = form.file_field :image, class: 'Job-images__list--file'
          %li.Job-images__list
            = form.label :image, class: "Job-images__list--img" do
              = icon('fas', 'image')
              = form.file_field :image, class: 'Job-images__list--file'
          %li.Job-images__list
            = form.label :image, class: "Job-images__list--img" do
              = icon('fas', 'image')
              = form.file_field :image, class: 'Job-images__list--file'
          %li.Job-images__list
            = form.label :image, class: "Job-images__list--img" do
              = icon('fas', 'image')
              = form.file_field :image, class: 'Job-images__list--file'
      .Vacancy-contents
        .Vacancy-title
          【求人詳細記入】
        %table.Vacancy-infos
          %tr.Vacancy-item
            %td.Vacancy-item__left
              勤務地
            %td.Vacancy-item__right
              = form.text_field :text ,maxlength: 30, placeholder: 'ここに文章を入力してください'
          %tr.Vacancy-item
            %td.Vacancy-item__left
              給与
            %td.Vacancy-item__right
              = form.text_field :text ,maxlength: 30, placeholder: 'ここに文章を入力してください'
          %tr.Vacancy-item
            %td.Vacancy-item__left
              アクセス
            %td.Vacancy-item__right
              = form.text_field :text ,maxlength: 30, placeholder: 'ここに文章を入力してください'
          %tr.Vacancy-item
            %td.Vacancy-item__left
              勤務時間
            %td.Vacancy-item__right
              = form.text_field :text ,maxlength: 30, placeholder: 'ここに文章を入力してください'
          %tr.Vacancy-item
            %td.Vacancy-item__left
              曜日・日数
            %td.Vacancy-item__right
              = form.text_field :text ,maxlength: 30, placeholder: 'ここに文章を入力してください'
          %tr.Vacancy-item
            %td.Vacancy-item__left
              募集人数
            %td.Vacancy-item__right
              = form.text_field :text ,maxlength: 30, placeholder: 'ここに文章を入力してください'
          %tr.Vacancy-item
            %td.Vacancy-item__left
              契約期間
            %td.Vacancy-item__right
              = form.text_field :text ,maxlength: 30, placeholder: 'ここに文章を入力してください'
          %tr.Vacancy-item
            %td.Vacancy-item__left
              営業担当
            %td.Vacancy-item__right
              = form.text_field :text ,maxlength: 30, placeholder: 'ここに文章を入力してください'
          %tr.Vacancy-item
            %td.Vacancy-item__left
              都道府県
            %td.Vacancy-item__right
              = form.text_field :text ,maxlength: 30, placeholder: 'ここに文章を入力してください'
        .Staff-contents
          .Staff-contents__title
            【担当営業】
          .Sales-staffs
            .Sales-staff__name
              "山田 太郎"
            .Sales-staff__name
              "石倉 香"
            .Sales-staff__name
              "山口 上"
        .Pr-contents
          .Pr-title
            PRポイント
          .Pr-box
            .Pr-box__text
              残業ほぼなしカジュアルOK！
            .Pr-box__text
              あっとホーム環境◎
            .Pr-box__text
              引継ぎしっかり！
            .Pr-box__text
              引継ぎしっかり
      .Button-wrapper
        = form.submit '掲載する', class: 'Button-wrapper__button'

app/views/tops/show.html.haml
.Wrapper
  .Title-wrapper
    仕事内容
  .Job-wrapper
    .Upper-contents
      .Upper-contents__name
        残業なしカジュアルOK！ あっとホーム環境◎ 引継ぎしっかり◎
    .Pr-contents
      .Pr-title
        PRポイント
      .Pr-box
        .Pr-box__text
          テストテストテストテストテストテストテストテスト
        .Pr-box__text
          テストテストテストテストテストテストテストテスト
        .Pr-box__text
          テストテストテストテストテストテストテストテスト
    .Image-contents
      %ul.Job-images
        %li.Job-images__list1
          1
        %li.Job-images__list
          2
        %li.Job-images__list
          3
        %li.Job-images__list
          4
        %li.Job-images__list
          5
    .Vacancy-contents
      %table.Vacancy-infos
        %tr.Vacancy-item
          %td.Vacancy-item__left
            勤務地
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            給与
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            アクセス
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            勤務時間
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            曜日・日数
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            募集人数
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            契約期間
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            営業担当
          %td.Vacancy-item__right
            テスト
        %tr.Vacancy-item
          %td.Vacancy-item__left
            都道府県
          %td.Vacancy-item__right
            テスト
      .Question-box
        = link_to 'http://www.pikawaka.com', class: "Question-box__btn" do
          チャットで質問する！

  .Review-wrapper
    .Review-wrapper__title
      みんなの口コミ
    .Review-wrapper__list
      .Review-infomation
        .Review-infomation__left
          .Review-infomation__left--good
          【よかった点】
          .Review-infomation__left--text
          つつつつううううううううううううううううううう
          .Review-infomation__left--good
          【わるかった点】
          .Review-infomation__left--text
          えええええええええええええええええええええええ
        .Review-infomation__right
          = link_to 'http://www.pikawaka.com', class: "Review-infomation__right--edit" do
            編集
          = link_to 'http://www.pikawaka.com', class: ".Review-infomation__right--destroy" do
            削除
    .Review-wrapper__up
      = image_tag 'image.png', class: 'Review-wrapper__up--image'
    .Review-wrapper__title
      感想を教えて！
    .Review-wrapper__form
      = form_with url: "#" do |form|
        .Review-box
          .Review-box__good
            【よかった点】
          = form.text_area :text, maxlength: 250, class: 'Review-box__text', placeholder: 'ここに文章を入力してください'
          .Review-box__bad
            【わるかった点】
          = form.text_area :text, maxlength: 250, class: 'Review-box__text', placeholder: 'ここに文章を入力してください'
        .Review-button
          = form.submit 'レビュー'